apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pg-admin-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
