apiVersion: v1
kind: Service
metadata:
  name: pg-admin-cluster-ip-service.yaml
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
    - port: 5050
      targetPort: 5050
