apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingresse-test
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: web.globalproxy.online
    http:
      paths:
      - backend:
          serviceName: app
          servicePort: 80
        path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: monitor.globalproxy.online
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
