apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: asengame/flask-docker:v1
          ports:
            - name: app-port
              containerPort: 80
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
        - name: init-mydb-pod
          image: asengame/init-container
          command: ['sh', '-c', './wait-for-it.sh postgres:5432 -t 0']
        - name: init-redis
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup redis.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for redis; sleep 2; done"]
