apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: app-postgres
      containers:
        - name: postgres
          image: postgres:12.10-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: flask_db_admin
            - name: POSTGRES_DB
              value: flask_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/psql/data
